name: tuwunel-tak
title: tuwunel-tak
summary: UnOfficial release of Tuwunel
description: |
  **Tuwunel is a featureful Matrix homeserver.**
  
  * You can use it instead of Synapse with your favorite client, bridge or bot. It is written entirely in Rust to be a scalable, low-cost, enterprise-ready, community-driven alternative, fully implementing the Matrix Specification for all but the most niche uses.
  * This project is the official successor to conduwuit after it reached stability. Tuwunel is now used by many companies with a vested interest in its continued development by full-time staff. It is primarily sponsored by the government of Switzerland 🇨🇭 where it is currently deployed for citizens.

  * The API service is accessible by default at http://localhost:8008

  * See https://github.com/matrix-construct/tuwunel for more details.

  **Tuwunel**
  * Service is restarted on any condition.

  **Post install command to check if service is running well and responses:**
  
  sudo snap logs tuwunel-tak
  
  **Post install commands required to access media folders and see resources, if your database or any other file need to be stored outside the snap data area:**

  sudo snap connect tuwunel-tak:removable-media

  sudo snap connect tuwunel-tak:mount-observe
  
  **!!! Files can only be written in a directory owned by `root` !!!**
  **!!! `/home` base directory content is not readable !!!**
  
  This is due to current behavior and restrictions of snaps by Canonical.
  Check common doc in FAQ if you want to setup data in `/home` directory.
  
  **Minimal configuration**
  * Configuration file 'tuwunel.toml' is located in "$SNAP_DATA/etc/tuwunel/tuwunel.toml" accessible through "/var/snap/tuwunel-tak/current/etc/tuwunel/tuwunel.toml" with default snapd installation
  
  * If you want to store your database in the snap data area:
  
  database_path = "var/lib/tuwunel" # 'var/lib/tuwunel' and not '/var/lib/tuwunel' ; your database will be saved in "$SNAP_DATA/var/lib/tuwunel" this way
  
  * New user registration is disabled by default (cf. @'allow_registration')
  * etc... cf. toml-integrated doc and Tuwunel official doc
  
  **Information:**
  * Configuration file is automatically created if not found in "$SNAP_DATA/etc/tuwunel/" ; copied from original source configuration file
  * Configuration file is never updated (for now) ; if changes are required with new software release, it is your full responsibility to update it.
website: https://github.com/matrix-construct/tuwunel
source-code: https://github.com/TehAppKiller/tuwunel-tak
issues: https://github.com/TehAppKiller/tuwunel-tak/issues
contact: mailto:tehappkiller@proton.me
donation: https://whydonate.com/en/fundraising/help-teh-devz
license: MIT
icon: icon.svg
grade: stable
confinement: strict
base: core24
adopt-info: tuwunel
platforms:
  amd64:
  arm64:

apps:
  tuwunel:
    command: bin/run-tuwunel.sh
    daemon: simple
    restart-condition: always
    plugs:
      - mount-observe
      - network
      - network-bind
      - removable-media
      - home # useless for now ; if daemon snaps are allowed to read /home folder one day...
    environment:
      TUWUNEL_CONFIG: $SNAP_DATA/etc/tuwunel/tuwunel.toml

parts:
  tuwunel:
    plugin: nil
    source: .
    override-pull: |
    
      # Architecture
      case "$CRAFT_ARCH_BUILD_FOR" in
        amd64) SRC_ARCH="x86_64-v3" ;;
        arm64) SRC_ARCH="aarch64-v8" ;;
      esac

      # Pull
      rm -rf $CRAFT_PART_SRC/{,.[!.],..?}*
      download_url=$(curl -sL https://api.github.com/repos/matrix-construct/tuwunel/releases/latest | grep "$SRC_ARCH-linux-gnu-tuwunel\." | sed -nre "s/^.*\"browser_download_url\": \"([^\"]*.deb)\".*/\1/p")
      wget "${download_url}" -O srcfile

      craftctl default
      
    override-build: |
    
      # Architecture
      case "$CRAFT_ARCH_BUILD_FOR" in
        amd64) SRC_ARCH="x86_64-v3" ;;
        arm64) SRC_ARCH="aarch64-v8" ;;
      esac
    
      # Get Last Source Tag version and Check Snap (with same Source) version
      src_version=$(curl -sL https://api.github.com/repos/matrix-construct/tuwunel/releases/latest | grep "$SRC_ARCH-linux-gnu-tuwunel\.deb" | sed -nre "s/^.*\/download\/v([^\/]*)\/.*/\1/p")
      echo "Source last tag: ${src_version}"
      snap_last_version=$(curl -sL -H "Snap-Device-Series: 16" "https://api.snapcraft.io/v2/snaps/info/tuwunel-tak?architecture=${CRAFT_ARCH_BUILD_FOR}&fields=version" | sed -nre "s/^.*\"stable\"\,\"track\"\:\"latest\"\}\,\"version\"\:\"([^\"]*)\".*/\1/p");
      echo "Snap last version: ${snap_last_version}"
      snap_build_with_same_version=$(echo $snap_last_version | sed -nre "s/^($src_version.*).*/\1/p");
      # Same version ?
      if [ -z "$snap_build_with_same_version" ]
      then
        new_snap_version="${src_version}";
      else
        # Get snap build version
        snap_build=$(echo $snap_build_with_same_version | sed -nre 's/^.*-v([0-9]*).*/\1/p');
        # Already a build version ?
        if [ -z "$snap_build" ]
        then
          # init @v2
          new_snap_build="2";
        else
          # increment @v+1
          new_snap_build=$(($snap_build+1));
        fi

        new_snap_version="${src_version}-v${new_snap_build}";
      fi

       craftctl set version=$new_snap_version

      # Build
      dpkg -x srcfile $CRAFT_PART_INSTALL/

      craftctl default
    build-packages:
      - curl
      - wget
      - dpkg

  local:
    plugin: dump
    source: snap/local
    override-prime: |
      craftctl default
      chmod +rx $CRAFT_PRIME/bin/run-tuwunel.sh
      
